'use strict';
const tracks={
 rhythm:{name:'Rhythm & flow',observe:'Choose a short Tarantula passage. Where do you hear syllables land relative to the pulse, and where does the voice leave space?',exercise:'Tutor exercise: write two original lines. Tap a comfortable pulse and speak them once evenly, then again with one changed pause or stressed syllable. Compare the feeling and clarity. No DAW needed.',hint:'Tap an even pulse. Listen for one word landing with the tap and one gap between phrases. Describe that contrast in your own words.'},
 voice:{name:'Vocal contrast',observe:'Choose a short Tarantula passage. Describe one change in delivery: emphasis, softness, pitch range, or texture. What does that change make you feel?',exercise:'Tutor exercise: speak one original line twice, changing only emphasis or softness. Choose the version that supports your intended feeling. Keep the volume comfortable; no imitation of Ren’s voice is required.',hint:'Focus on one variable. Does a word become softer, more forceful, or more sustained? You can describe it without musical terminology.'},
 space:{name:'Arrangement & space',observe:'Choose a short Tarantula passage. What layer enters, leaves, or becomes less prominent? Describe what happens to your attention.',exercise:'Tutor exercise: make a four-bar original loop with a pulse, your voice, and one texture. Remove the texture briefly, then bring it back. Compare the effect. Without a DAW, tap the pulse and use a hum as the texture.',hint:'Listen once for the voice, once for the pulse, and once for another texture. Notice whether any of those becomes more or less prominent.'},
 rights:{name:'Beats & release planning',observe:'For a beat you own or are considering licensing, identify one term or unanswered question: stream limits, permitted uses, samples, splits, or who can grant permission. Do not share personal contract details.',exercise:'Tutor exercise: create a short loop entirely from your own new material. Label each part by creator and keep a stem for each. Separately write one question for the beat supplier about sample permissions or license limits. Re-recording a melody does not by itself clear composition rights or guarantee full ownership.',hint:'Can you identify the agreement, the permitted use, and the origin of every sound? If something is missing, put it in your questions list rather than guessing.'}
};
const log=document.querySelector('#conversation'),choices=document.querySelector('#choices'),reply=document.querySelector('#reply'),status=document.querySelector('#status'),progress=document.querySelector('#progress');
let stage='focus',track=null,history=[],goal='',evidence='';
function add(who,text){history.push({who,text});const el=document.createElement('div');el.className='message'+(who==='You'?' student':'');const name=document.createElement('span');name.className='speaker';name.textContent=who;el.append(name,document.createTextNode(text));log.append(el);log.scrollTop=log.scrollHeight;}
function options(items){choices.replaceChildren();items.forEach(([label,value])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>submit(value||label));choices.append(b);});}
function update(label,placeholder){progress.textContent=label;reply.placeholder=placeholder;status.textContent='';}
function select(value){const v=value.toLowerCase();if(/beat|lease|rights|licens|sample|kujo/.test(v))return 'rights';if(/rhythm|flow|cadence|rap/.test(v))return 'rhythm';if(/vocal|voice|delivery/.test(v))return 'voice';if(/arrang|space|layer|mix|production/.test(v))return 'space';return null;}
function submit(raw){if(raw==='NEW_FOCUS'){reset();reply.focus();return;}const text=raw.trim();if(!text){status.textContent='Write a reply or choose a suggested response.';return;}if(text.length>1200){status.textContent='Keep your reply under 1,200 characters.';return;}reply.value='';add('You',text);
 if(/^(pause|stop)$/i.test(text)){add('Tutor','Take a break. Your place stays in this tab. Continue when you are ready, or download your conversation before closing.');return;}
 if(/what.*ren.*(said|say)|ren.*(quote|intention|plugin|bpm)|exact.*(tempo|key)/i.test(text)){add('Tutor','I do not have a verified transcript or those production details. Open the artist conversation in the source panel and bring back a timestamp with a brief paraphrase. I will keep your report separate from verified artist statements. Your lesson is still at the same step.');return;}
 if(stage==='focus'){const selected=select(text);if(!selected){add('Tutor','Which focus is closest to your goal: rhythm and flow, vocal contrast, arrangement and space, or beats and release planning?');return;}track=tracks[selected];stage='goal';options([['I’m starting without a DAW'],['I have a DAW or instrument']]);update('1 of 5 • Your goal','What do you want to communicate, and what tools do you have?');add('Tutor','Let’s explore '+track.name.toLowerCase()+'. What do you want your own music to communicate, and what tools can you use? A tap, hum, or spoken line is enough.');}
 else if(stage==='goal'){goal=text;stage='source';options([['Use my own listening observation'],['I’ll bring a source moment']]);update('2 of 5 • Find a source moment','A timestamp and brief paraphrase, or your own observation.');add('Tutor',track===tracks.rights?'Your tools and goal set the scope. This release-planning branch uses general learning exercises. The supplied Kujo/Sick Boi account has not been verified against an original transcript; I will not present it as established facts. What source or license term would you like to inspect? You can also continue with your own questions.':'Use the linked Knox Hill & Ren conversation to find an explanation relevant to your goal. What timestamp and brief paraphrase would you like to work from? If you prefer, continue with your own listening observation.');}
 else if(stage==='source'){evidence=text;stage='observe';options([['I need a hint']]);update('3 of 5 • Notice one thing','Describe one specific observation or unanswered question.');add('Tutor',(text==='Use my own listening observation'?'We’ll work from your listening, without attributing it to Ren.':text==='I’ll bring a source moment'?'Bring the moment into your next reply. Until it is checked, it remains your source report.':'Source note recorded as your report, pending verification—not a verified quotation.')+'\n\n'+track.observe);}
 else if(stage==='observe'){if(text==='I need a hint'){add('Tutor',track.hint);return;}stage='attempt';options([['I tried it without a DAW'],['I need a smaller exercise']]);update('4 of 5 • Try an original exercise','Tell me what you tried and what changed.');add('Tutor','Your note gives us something concrete to test. '+track.exercise+'\n\nWhat did you try, and what changed? I can respond to your written description, but cannot hear or evaluate a recording here.');}
 else if(stage==='attempt'){if(text==='I need a smaller exercise'){add('Tutor',track===tracks.rights?'Start with one original sound and label who created it. Write just one permission question.': 'Use one original line and change only one pause or emphasis. Which version feels closer to your goal?');return;}stage='reflect';options([['Clarity'],['Energy'],['Space'],['I’m not sure yet']]);update('5 of 5 • Reflect and revise','Which change helped your goal? What will you change next?');add('Tutor',/muddy|crowded|unclear|too much/i.test(text)?'You reported a clarity problem. For the next comparison, remove one layer or shorten one phrase; keep everything else the same. Which result better supports your goal?':/hard|difficult|fast|can.t/i.test(text)?'You reported difficulty. Make the next attempt shorter or use a slower comfortable pulse. Which single change would let you compare the versions more clearly?':'Compare your two attempts against your goal: '+goal+'\nWhich change helped, and what single change will you try next?');}
 else{add('Tutor','Reflection recorded. Keep one change for your next attempt, compare it with the previous version, and return to the source when you need to check an artist explanation. This scripted demo records your reflections; it does not grade musical correctness. You can keep reflecting, download this conversation, or start another focus.');options([['Try another focus','NEW_FOCUS']]);update('Lesson reflection complete','Add another reflection, or start a new focus.');}
}
// All messages use textContent; student input is never HTML.
function reset(){stage='focus';track=null;goal='';evidence='';history=[];log.replaceChildren();reply.value='';update('Choose a focus','Choose a focus above, or describe what you want to learn.');add('Tutor','What would you like to learn from Tarantula and bring into your own music? Choose a focus. We’ll use published source material, try one original exercise, and reflect on your result.');options(Object.entries(tracks).map(([key,t])=>[t.name,key==='rights'?'beat licensing':key==='space'?'arrangement':key==='voice'?'vocal':'rhythm']));}
document.querySelector('#reply-form').addEventListener('submit',event=>{event.preventDefault();submit(reply.value);reply.focus();});
document.querySelector('#hint').addEventListener('click',()=>add('Tutor',track?track.hint:'Choose one musical skill you want to practice. You can start with rhythm by tapping a pulse while speaking an original line.'));
document.querySelector('#restart').addEventListener('click',()=>{reset();reply.focus();});
document.querySelector('#export').addEventListener('click',()=>{const intro='Tarantula — Ren-inspired tutor\nReconstructed scripted example. Student source reports are unverified.\nSources: https://www.youtube.com/watch?v=0DTrjpIb4QI and https://www.youtube.com/watch?v=8t4wisfnf4M\n\n';const blob=new Blob([intro+history.map(m=>m.who+': '+m.text).join('\n\n')],{type:'text/plain;charset=utf-8'});const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='tarantula-lesson.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#export-status').textContent='Conversation download requested.';});
reset();
